server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hexagonal?autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: hexagonal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true # Initializes mySQL Schema structure
    hibernate:
      dll-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
  output:
    ansi:
      enabled: ALWAYS